services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    container_name: mlflow
    ports:
      - "5050:5050"
    volumes:
      # Persist MLflow DB and artifacts
      - mlflow-data:/mlflow

  serving:
    build:
      context: .
      dockerfile: serving/Dockerfile
    container_name: serving
    image: serving:latest
    ports:
      - "8080:8080"
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://localhost:5050}
      MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME:-sisdata}

  models:
    build:
      context: .
      dockerfile: models/Dockerfile
    container_name: models
    image: models:latest
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://localhost:5050}
      MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME:-sisdata}
      COMMIT_SHA: "local-dev"
    volumes:
      # Persist training data
      - train-data:/app/train-data

volumes:
  mlflow-data:
  train-data: