name: 1 - Continuous Integration
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}

jobs:
  test-unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Setup python environment
        run: |
          pip install uv
          uv sync
      - name: Run unit tests
        run: |
          uv run pytest tests/test_api.py -v

  build-images:
    # Passed tests, now build docker images for training and serving
    runs-on: self-hosted
    needs: test-unit
    steps:
      - uses: actions/checkout@v4

      # Build images for serving and training services using Docker Compose
      - name: Build images with Docker Compose
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose build training serving

      # Log in to GitHub Container Registry (GHCR)
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the built images to GHCR
      # These images will be tagged with the commit SHA and can be pulled in later stages for testing and deployment
      # For more info on how they are named and tagged, see the docker-compose.yml file
      - name: Push images
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker compose push training serving
