name: 2 - Continuous Delivery
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  # Runs when the previous stage finished
  workflow_run:
    workflows: ["1 - Continuous Integration"]
    types: [completed]

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}

jobs:
  train-model:
    # Run only if previous stage finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    timeout-minutes: 0

    steps:
      # Checkout the repository to access the code and configuration files
      - uses: actions/checkout@v4
      # Log in to GitHub Container Registry (GHCR)
      # We will get the serving image with tag staging from here to validate
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Download and run the training image built in the previous stage
      - name: Train models
        env:
          TRAINING_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}/training:${{ github.sha }}
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_EXPERIMENT_NAME: ${{ env.MLFLOW_EXPERIMENT_NAME }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          docker compose run --pull always training

      # Start the serving container to validate the trained model
      - name: Start serving container
        env:
          SERVING_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}/serving:${{ github.sha }}
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_EXPERIMENT_NAME: ${{ env.MLFLOW_EXPERIMENT_NAME }}
          SERVING_PORT: 8080
        run: |
          docker compose up -d --pull always serving

          # Wait for FastAPI to be ready
          sleep 10

      # Run end to end tests, this will test the serving app to see if it is working ok
      # Additional metrics and verification can assess performance metrics as well
      - name: Run Staging tests
        run: uv run pytest tests/test_e2e.py -v

      - name: Show container logs on failure
        if: failure()
        run: |
          echo "=== FastAPI logs ==="
          docker logs serving-app || true

      # Log in to GitHub Container Registry (GHCR)
      # This is the repository where we will upload our images once they have been validated
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tag serving image with staging; this image will be used for further testing in staging
      # Push serving image to repository
      - name: Push serving staging image
        run: |
          docker tag ${{ env.REGISTRY }}/${{ github.repository }}/serving:${{ github.sha }} \
                     ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging

      # Promote selected model to staging to be further validated
      - name: Promote model to staging
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME: ${{ env.MLFLOW_MODEL_NAME }}
          FROM_ALIAS: best
          TO_ALIAS: staging
        run: |
          set -xe
          uv run python -u model_promotion/promote_model.py
