name: 3 - Continuous Staging
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  # Runs when the previous stage finished
  workflow_run:
    workflows: ["2 - Continuous Delivery"]
    types: [completed]

  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}
  SERVING_URI: ${{ vars.SERVING_URI }}

jobs:
  stage-tests:
    # Run only if previous stage finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Setup python environment
        run: |
          pip install uv
          uv sync

      # Log in to GitHub Container Registry (GHCR)
      # We will get the serving image with tag staging from here to validate
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Download and start the serving image validated in the previous stage
      - name: Start serving container
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: staging
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_EXPERIMENT_NAME: ${{ env.MLFLOW_EXPERIMENT_NAME }}
          SERVING_PORT: 8080
        run: |
          docker compose up -d --pull always serving

          # Wait for FastAPI to be ready
          sleep 10

      # ===================== Run tests against staging environment =====================
      # Here we are just running the same E2E tests, but in real systems we would run
      # the system in a preproduction environment, that would manually or automatically
      # apply  A/B testing, shadow testing and other approaches to measure
      # and validate the performance of the model before moving to production
      - name: Run Staging tests
        env:
          FASTAPI_BASE_URL: ${{ env.SERVING_URI }}
        run: uv run pytest tests/test_e2e.py -v

      # When reaching the stage both the serving and the model will have passed
      # the necessary tests and we promote to production
      - name: Promote model to production
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME: ${{ env.MLFLOW_MODEL_NAME }}
          FROM_ALIAS: staging
          TO_ALIAS: production
        run: uv run python model_promotion/promote_model.py

      # Tag the serving image with production tag
      # This is the image that will be used to deploy the system
      - name: Push production container tag
        run: |
          docker tag ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging \
                     ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
